# Perceptron_Implementation

In [2]:
import joblib 
import numpy as np
import pandas as pd 
import os
import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")

In [3]:
class Perceptron:
    def __init__(self , eta : float=None ,epochs : int=None):## eta is learning rate(n)
        self.weights = np.random.randn(3) * 1e-4 ## it will Take the Random Weights 3(w1 , w2 , w3)
        self.eta = eta
        self.epochs = epochs
        
    def _z_outcome(self, inputs, weights): ## Matrix Multiplication weights and bias x1w1 + x2w2 +w0x0(bias)
        return np.dot(inputs, weights)
    
    def activation_function(self, z): ## Step Activation Function
        return np.where(z > 0, 1, 0)
        
    def fit(self , X , y): ## Fit the x and y
        self.X = X
        self.y = y
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] ## we add bias(-1) to our x 
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
            
        
        

In [5]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [6]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y
X, y = prepare_data(df_OR)

In [7]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [8]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [9]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.20002365  0.19994736 -0.29982633]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.20002365  0.19994736 -0.19982633]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.20002365  0.19994736 -0.09982633]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype

In [10]:
model_or.predict(X=[[0,0]])  ## It will Predict correctly

array([0])

## Now We Use And Gate

In [11]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)

df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [13]:
X, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA, epochs=EPOCHS)

model_and.fit(X, y)


X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 1 0 0]
error: 
0    0
1   -1
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[9.99246098e-02 5.10247861e-05 1.98426740e-06]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[-7.53902020e-05 -9.99489752e-02  2.00001984e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[9.99246098e-02 5.10247861e-05 1.00001984e-01]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    

In [14]:
model_and.predict(X=[[1, 0]]) ### It again gives correct answer

array([0])